### PR TITLE
Export as a module as well as CLI tool

### PR DESCRIPTION
**Pull request by hollandben**
Hi - we started using this module to format our logs so that they were formatted correctly when ingested into Stackdriver via `stdout`. For a regular application server, it works great, but when trying to use it with for Cloud Functions, we were unable to pipe the output through to this package.

This PR exposes a ready made stream which can be imported into code and passed to `pino` as a destination stream. There's an example in the readme.

Let me know your thoughts (or if there is a way of getting it working with Cloud Functions as is).

### CODE REVIEW

**Comment by ianwalter** [comment]
Looks good to me. We're not using Cloud Functions so not sure what the issue is. Do you mind fixing the lint issue (`yarn lint --fix`) and renaming bin.js to cli.js (just what I'm used to)?

**Comment by hollandben** [comment]
Sure, will make those changes and leave it to you to merge. I'm currently looking at trying to write a test for this use case, but it's proving tricky.

The problem when using Cloud Functions is that it requires in the file referenced in `main` inside `package.json`, meaning there's only a single process running and no way to pipe the output somewhere else.

**Comment by ianwalter** [comment]
Thanks! I can add a test a little later before publish.

**Comment by hollandben** [comment]
The version on `npm` is still showing as `1.1.0`. Can you publish the latest version there please: 😁

**Pull request merged**
